# What Python version is installed where:
# http://www.appveyor.com/docs/installed-software#python

environment:
  PYTHONUNBUFFERED: 1
  MINICONDA: C:\\Miniconda3-x64
  matrix:
    - PYTHON: "C:\\Python35"
      TOX_ENV: "py35"

    - PYTHON: "C:\\Python36"
      TOX_ENV: "py36"

    - PYTHON: "C:\\Python37"
      TOX_ENV: "py37"

init:
  - "%PYTHON%/python -V"
  - mkdir C:\Users\appveyor\.conda
  - call %MINICONDA%\Scripts\activate.bat

install:
  - "%PYTHON%/Scripts/pip install -U --user pip"
  - "%PYTHON%/Scripts/pip install -U --user tox wheel"

build: false # Not a C# project, build stuff at the test step instead.

test_script:
  - "%PYTHON%/python -m tox -e %TOX_ENV%"

after_test:
  - "%PYTHON%/python setup.py bdist_wheel"
  - ps: "ls dist"

artifacts:
  - path: dist\*
#on_success:
#  - TODO: upload the content of dist/*.whl to a public wheelhouse
